spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 947008366981-sdebqavdb1a35mqs2v7uidjinv8kn3kl.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

          naver:
            client-id: EQc9xfQ_7bZqTPMTGQUI
            client-secret: _AmDuhBpOU
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}" # (== http://localhost:8080/login/oauth2/code/naver)
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
              - profile_image
            client-name: Naver

          kakao:
            client-id: 603b5f0afce00d137de8414a10b38b99
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}" # (== http://localhost:8080/login/oauth2/code/kakao)
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - profile_image
              - account_email
            client-name: Kakao


        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response

          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id

