spring:
  profiles:
    include: oauth
  h2:
    console:
      enabled: true

  jpa:
    show-sql: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
